# Generated by Django 5.0.4 on 2024-09-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(default='Default Company Name', max_length=100),
        ),
    ]
